Add more colourised build output.

diff --git a/src/Geo-IP/IPFire/src/Makefile.Windows b/src/Geo-IP/IPFire/src/Makefile.Windows
--- a/src/Geo-IP/IPFire/src/Makefile.Windows
+++ b/src/Geo-IP/IPFire/src/Makefile.Windows
@@ -347,7 +347,7 @@ $(OBJ_DIR)/%.obj: %.c | $(OBJ_DIR) $(CC).args
 	$(call C_compile, $@, $<)
 
 $(CC).args: $(THIS_FILE)
-	$(call green_msg, All CFLAGS are in $@)
+	$(call green_msg, All CFLAGS are in $(BRIGHT_WHITE)$@)
 	$(call create_resp_file, $@, -c $(CFLAGS))
 
 %.i: %.c FORCE $(OBJ_DIR)/cpp-filter.py $(CC).args
@@ -448,12 +448,12 @@ test-%.exe: $(OBJ_DIR)/test-%.obj $(IMPORT_LIB)
 	$(call link_EXE, $@, $^)
 
 run_tests runtests: $(TEST_PROGS)
-	for p in $^ ; do                            \
-	    echo -e "\n\e[1;32mRunning $$p:\e[0m" ; \
-	    ./$$p ;                                 \
-	    if [ $$? -ne 0 ]; then                  \
-	       echo -e "\e[1;31mFailed!\e[0m" ;     \
-	  fi ;                                      \
+	for p in $^ ; do                                    \
+	    echo -e "\n\e[1;32mRunning \e[1;37m$$p:\e[0m" ; \
+	    ./$$p ;                                         \
+	    if [ $$? -ne 0 ]; then                          \
+	       echo -e "\e[1;31mFailed!\e[0m" ;             \
+	  fi ;                                              \
 	done
 
 run_export_test: py3_module
@@ -513,13 +513,13 @@ py3_install/_location.pyd: $(PY_OBJ) $(IMPORT_LIB) $(OBJ_DIR)/_location.res | py
 	$(call link_PYD, $@, $(PY_OBJ) $(IMPORT_LIB) $(OBJ_DIR)/_location.res $(PY_LIB))
 
 py3_install/location.py: scripts/location.in
-	$(call green_msg, Generating $@)
-	sed -e 's|@VERSION@|$(VERSION)|' -e 's|@databasedir@|$(DATABASE_DIR)|' < $< > $@
+	$(call generate, $@, #)
+	sed -e 's|@VERSION@|$(VERSION)|' -e 's|@databasedir@|$(DATABASE_DIR)|' < $< >> $@
 	@echo
 
 py3_install/location-importer.py: scripts/location-importer.in
-	$(call green_msg, Generating $@)
-	sed -e 's|@VERSION@|$(VERSION)|' -e 's|@databasedir@|$(DATABASE_DIR)|' < $< > $@
+	$(call generate, $@, #)
+	sed -e 's|@VERSION@|$(VERSION)|' -e 's|@databasedir@|$(DATABASE_DIR)|' < $< >> $@
 	@echo
 
 clean:
@@ -558,14 +558,11 @@ XSLTPROC_FLAGS += --nonet docbook.xsl
 #
 # The following assumes you have a MSys/Cygwin 'echo.exe' program with colour support.
 #
-BRIGHT_RED   = \e[1;31m
 BRIGHT_GREEN = \e[1;32m
 BRIGHT_WHITE = \e[1;37m
 
 colour_msg = @echo -e "$(1)\e[0m"
 green_msg  = $(call colour_msg,$(BRIGHT_GREEN)$(strip $(1)))
-white_msg  = $(call colour_msg,$(BRIGHT_WHITE)$(strip $(1)))
-red_msg    = $(call colour_msg,$(BRIGHT_RED)$(strip $(1)))
 
 define Warning
   $(1)
@@ -576,7 +573,7 @@ define Warning
 endef
 
 define generate
-  $(call green_msg, Generating $(1))
+  $(call green_msg, Generating $(BRIGHT_WHITE)$(strip $(1)))
   $(file > $(1),$(call Warning,$(strip $(2))))
 endef
 
@@ -609,7 +606,7 @@ endef
 define link_EXE
   $(file  > $(OBJ_DIR)/check-for-unused-libs.py,if 1:)
   $(file >> $(OBJ_DIR)/check-for-unused-libs.py,$(CHECK_FOR_UNUSED_LIBS_PY))
-  $(call green_msg, Linking $(1))
+  $(call green_msg, Linking $(BRIGHT_WHITE)$(strip $(1)))
   $(call create_resp_file, link.args, $(LDFLAGS) $(2))
   link -out:$(strip $(1)) @link.args > link.tmp
   @cat link.tmp >> $(1:.exe=.map)
@@ -626,7 +623,7 @@ endef
 define link_DLL
   $(file  > $(OBJ_DIR)/check-for-unused-libs.py,if 1:)
   $(file >> $(OBJ_DIR)/check-for-unused-libs.py,$(CHECK_FOR_UNUSED_LIBS_PY))
-  $(call green_msg, Linking $(1))
+  $(call green_msg, Linking $(BRIGHT_WHITE)$(strip $(1)))
   $(call create_resp_file, link.args, $(LDFLAGS) -dll -implib:$(strip $(3)) $(2))
   link -out:$(strip $(1)) @link.args > link.tmp
   @cat link.tmp >> $(1:.dll=.map)
@@ -642,7 +639,7 @@ endef
 define link_PYD
   $(file  > $(OBJ_DIR)/check-for-unused-libs.py,if 1:)
   $(file >> $(OBJ_DIR)/check-for-unused-libs.py,$(CHECK_FOR_UNUSED_LIBS_PY))
-  $(call green_msg, Linking $@)
+  $(call green_msg, Linking $(BRIGHT_WHITE)$(strip $(1)))
   $(call create_resp_file, link.args, $(LDFLAGS) -dll -libpath:$(PY_ROOT)/libs $(2))
   link -out:$(strip $(1)) @link.args > link.tmp
   @cat link.tmp >> $(1:.pyd=.map)
